### ISSUE TITLE
Normalizer. What features needed out of box?

### ISSUE THREAD

**Issue by puzrin** [markdown-it/linkify-it#1]
Linkification process expect 2 additional steps:

1. Links normalization
2. Text normalization

Adding too many features tend to api clobbering. Instead i'd prefer to simplify modifications. Some things i know about (with unknown usefulness):

- text
  - decode encoded texts
  - drop `http://` (but don't drop for links with user/pass)
  - drop `www`
  - cut length (leave domain & tail, cut the middle & query)
- url
  - usually, nothing needed, but it would be nice to correctly encode host + path + query

---

1. It would be interesting to get feedback from big deployments, how do they care about links.
2. Do we need to enchance normalization in this pkg, or move to plugins?

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/markdown-it/linkify-it)

**Comment by hemanth** [comment]
Something like:

* [urls-md](https://www.npmjs.com/package/urls-md)

* [ytmd](https://www.npmjs.com/package/ytmd)

Would be nice to have out of the box.

**Comment by puzrin** [comment]
Closed -  no longer actual. Methods are rewriteable.

**Comment by hemanth** [comment]
:+1:
