### ISSUE TITLE
Add .app TLD to tlds_default

### ISSUE THREAD

**Issue by buu700** [markdown-it/linkify-it#103]
The comment says not to submit a PR, so I won't do that, but .app is a pretty common/standard TLD nowadays and so seems to make sense in the default list.

**Comment by puzrin** [comment]
I see no reason for breaking changes, while you can configure TLD list as you wish.

**Comment by ursnj** [comment]
Yeah this is very much needed in recent days.

**Comment by buu700** [comment]
Just to clarify, I do have .app configured in my own application; I'm just suggesting that it would make more sense to have as a default.

**Comment by puzrin** [comment]
Any change of defaults is breaking. We avoid breaking changes when other alternatives available. Let's keep things as is. Sorry for inconvenience.

**Comment by buu700** [comment]
Got it, in that case it may just be something to consider for version 5.0.0.

**Comment by puzrin** [comment]
v5 may happen next day after "never" :). At current moment i have no ideas for v5.
