### ISSUE TITLE
Router admin login IP disclosed in source code

### ISSUE THREAD

**Issue by kristin-maughan** [markdown-it/linkify-it#110]
https://github.com/markdown-it/linkify-it/blob/9482bfec2532cfccb8d7a55f1b89facf54760b48/index.js#L480

Please consider removing the admin IP address from index.js line 480.  The same concept could be demonstrated using a dummy address and the admin IP does not itself add value above what a fictional address could provide.

![image](https://github.com/markdown-it/linkify-it/assets/10540595/975463e6-5357-4750-a771-b459560e5c95)

**Comment by rlidwka** [comment]
Thanks for the reporting this issue. After thorough investigation, I've determined that the quoted line does not constitute any kind of data breach.

If you want to suggest to use another fictional address instead, I'm very curious to know what it is.
