### ISSUE TITLE
Hostname with any 2-letter root zones are NOT ok.

### ISSUE THREAD

**Issue by kurdin** [markdown-it/linkify-it#12]
From your doc:
> hostname with any 2-letter root zones are ok.

This is not true and it cause text with ``node.js`` or ``io.js`` insert a links to not existed urls, http://node.js and http://io.js which is incorrect. It will cause more problem. 

Could you please fix this.

**Comment by puzrin** [comment]
Good catch! I'll see what can be done. As temporary solution, you can:

- reload tlds defaults https://github.com/markdown-it/linkify-it#tldslist-keepold
- disable flex links rule.

**Comment by kurdin** [comment]
@puzrin I will try that workaround, thanks for quick reply. 

btw, we are trying to resurrect forum.nodejs.ru (dead) for Russian JS experts and newcomers. New forum located on http://jsforum.ru and you Vitaly are more then welcome to join us. Your expertise is priceless! :+1:
