### ISSUE TITLE
False positives: version numbers

### ISSUE THREAD

**Issue by svbergerem** [markdown-it/linkify-it#13]
Version numbers like 0.5.0.0 are considered as IP addresses without a schema.

**Comment by puzrin** [comment]
I can add more strict condition for heading zeros, but it will not help with `1.5.0.0` and so on. I see only one possibility - more options to tune fuzzy links.

**Comment by svbergerem** [comment]
I agree. #14 would also fix this issue for diaspora* but I think for other projects it might help to disable IP adresses without schemas. (at least add a setting to enable/disable it)
