### ISSUE TITLE
Add an option to disable fuzzy links

### ISSUE THREAD

**Issue by svbergerem** [markdown-it/linkify-it#14]
AFAIK currently fuzzy links are enabled when http: is enabled. It would be great if there would be a separate setting. (Maybe even with the ability to enable www.... and http://... and disable everything else)

**Comment by puzrin** [comment]
Could you explain exactly, what this setting should do? Disable http links without schema, but still enable emails?

**Comment by svbergerem** [comment]
@puzrin sounds good. :)

**Comment by puzrin** [comment]
Take a look at api change & new option names. I've implemented features, but not sure than names are beautiful. If no better ideas, i'll do release.

**Comment by svbergerem** [comment]
I have no better idea right now. ;-) Thank you!
