### ISSUE TITLE
"//test" should not be linkified?

### ISSUE THREAD

**Issue by puzrin** [markdown-it/linkify-it#19]
Formally, that can be http(s) neutral link to local domain.

Should we be more restrictive with such links?

User could completely disable such type of links, because those are not very useful...

**Comment by artdude543** [comment]
Ideally could there not be a check with the regex after the `//` to check if the text afterwards is a domain / IP which would stop false positives. I use this module on a chat bot and it's a known bug that posting text messages such as `^///^` would trigger the bots link checking. But in actual fact the message was not a link.

**Comment by puzrin** [comment]
`//test` means correct local domain. you can not be sure if this is local domain or the part of text. I tend to drop `//` support at all because:

- too many false positives
- i'm not sure such links really exist in real world.

**Comment by artdude543** [comment]
True but some sites use the `//` for allowing usage of https / http. So the client would pick which one to use. I can't think of an easy fix for this or any one who has made a good check for a case like this.

Might be worth dropping support for now until a fix could be thought off. I'll try playing around with things to come up with something. But I think for now to prevent false positives might be worth dropping that support.

**Comment by puzrin** [comment]
`.add('//', null)` will help.

**Comment by artdude543** [comment]
Yeah I will get that in and test it out. Thanks for the help ^_^
