### ISSUE TITLE
Beta feedback - link recognition problems

### ISSUE THREAD

**Issue by puzrin** [markdown-it/linkify-it#2]
This ticket collects all link recognition problems during beta stage.

- Email user detection pattern is very primitive. Need advices on improvments.

---

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/markdown-it/linkify-it)

**Comment by MayhemYDG** [comment]
```
>example.com
>http://example.com
```
First one is recognized, but the `>` is linkified too.
Second one isn't recognized at all.

**Comment by puzrin** [comment]
Wow, good catch!

`>` has `symbol` class instead of `punctuation` as i expected https://github.com/mathiasbynens/unicode-7.0.0/blob/master/categories/S/regex.js#L1

Will fix soon.

**Comment by woxxy** [comment]
Thank you! :+1:

**Comment by puzrin** [comment]
Beta phase closed. Now create separate tickets for each edge case.
