### ISSUE TITLE
Trailing "-" not included in linkified url

### ISSUE THREAD

**Issue by Mumakil** [markdown-it/linkify-it#20]
It seems that some websites can have trailing `-` in their urls, which don't get included in the linkified url, thus breaking the link.

Example url:
http://www.bloomberg.com/news/articles/2015-06-26/from-deutsche-bank-to-siemens-what-s-troubling-germany-inc-

I understand that this might be a controversial topic, but I still feel that a `-` at the end of an url is a more usual case than having a `-` by mistake at the end like a period or a comma.

I could take a stab at getting a pr in for this if this sounds like a good change.

**Comment by puzrin** [comment]
Don't remember why i limited it. Probably side effect of long dash (`---`) markdown rule https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L56

I think, we can try proposed change and roll back if bad cases reported.

PR with tests will be accepted.
