### ISSUE TITLE
Triple dash ( --- ) terminating the parsing

### ISSUE THREAD

**Issue by pablolmiranda** [markdown-it/linkify-it#27]
Hi,

Why [triple dash](https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L56) terminate the url parsing?

**Comment by puzrin** [comment]
As written in comment `---` is usually a long dash.

**Comment by stephy** [comment]
@puzrin I am aware that --- is a long dash, but why is the long dash a problem? Some google docs have --- in their URL and they are legit URLs.

**Comment by puzrin** [comment]
@stephy `link---text` is link + long dash + text, in markdown (for example). That happens sometime, and that should not become a long link. As alternative, user can mark link explicitely: `<link---with---dashes>`.

False negative (terminated link) still leaves you an alternative way to fix situation. False positive (too long link) is not fixeable.

**Comment by puzrin** [comment]
Closing - works as intended.

**Comment by puzrin** [comment]
Fixed in 2.0.0, now configurable via options and not terminates by default.
