### ISSUE TITLE
Option for github-style fuzzy links

### ISSUE THREAD

**Issue by revin** [markdown-it/linkify-it#29]
Hello, thanks for the great markdown-it/linkify-it projects!

For [marky-markdown](https://www.npmjs.com/package/marky-markdown) we're trying to match github's style of linkification, which is somewhere between `fuzzyLink: true` and `false`. I wrote a [list of tests](https://github.com/npm/marky-markdown/pull/151#issuecomment-182585562) (duplicated below) to try and help us make sense of their algorithm, and it looks pretty straightforward: essentially the goal is:

* linkify fully qualified URLs, e.g., https://example.com/
* linkify valid hostnames starting with `www.` (including the four character string `www.` itself)
* for all other valid hostnames, turn linkification off

We're currently looking into creating a runtime patch we can use to wrap `LinkifyIt.prototype.test`, but if there was a simple option we could set on the `LinkifyIt` instance, that would be the ideal place to implement this behavior, if you thought it would be a good enhancement.

---
Here's my quick test case list:

* example.com
   * www.example.com
   * wwww.example.com
   * web.example.com
   * test.example.com
   * test.www.example.com
   * www.test.example.com
   * www0.test.example.com
   * www1.test.example.com
   * www2.test.example.com
* readme.md
   * www.readme.md
   * wwww.readme.md
   * web.readme.md
   * test.readme.md
   * test.www.readme.md
   * www.test.readme.md
* someone.name
   * www.someone.name
   * wwww.someone.name
   * web.someone.name
   * test.someone.name
   * test.www.someone.name
   * www.test.someone.name
* www.md
* www
* www.
* something www here
* something www. here
* //readme.md
* //www.readme.md

---
cc: @ashleygwilliams

**Comment by puzrin** [comment]
There are no need to intrude into test/match methods.

You can modify existing shemas or add new ones via [.add()](https://github.com/markdown-it/linkify-it#addschema-definition) method. Also, existing regexes are available as [Linkify.re`](https://github.com/markdown-it/linkify-it/blob/1.2.0/index.js#L382) for late hacking (after compile)

I'd recommend to look into sources. Code is quite simple.

**Comment by revin** [comment]
I see. I'd been looking at .test() because that's where the fuzzyLink stuff was happening, but I suppose adding a schema would work in this case because we do have a specific prefix. Not sure why I didn't think of that already.

Just so I'm clear, does your recommendation to implement this on our side mean you don't want to make this a linkify option? Or were you just giving advice that would make it smoother for us in the meantime?

**Comment by puzrin** [comment]
We have a bit different goals:

- You wish to linkify exactly as github does
- I whish to linkify according to modern needs + provide flexibility for modifications (if someone is not satisfied with defaults)

Look at [demo](http://markdown-it.github.io/linkify-it/), and try those patterns at github to see the difference. So, i don't like idea to support github-like likification because it's not perfect. I'd prefe if this will be done aside. Linkify should provide enougth flexibility to do it with reasonable efforts. But if you think, current API is not enougth - i'm ready to help.

**Comment by revin** [comment]
OK, fair enough. Thanks for the feedback!

**Comment by puzrin** [comment]
Closing?

**Comment by revin** [comment]
whoops, yes

**Comment by caub** [comment]
I think in the future, we could make things simpler maybe, instead of for example this config

```js
const md = require('markdown-it')({
  html: true,
  linkify: true,
  typographer: true
});
const LinkifyIt = require('linkify-it');

LinkifyIt.prototype.normalize = function normalize(match) {
  // https://github.com/markdown-it/linkify-it/blob/master/index.js#L614
  if (!match.schema) { match.url = 'https://' + match.url; }

  if (match.schema === 'mailto:' && !/^mailto:/i.test(match.url)) {
    match.url = 'mailto:' + match.url;
  }
};

md.linkify.add('@', {
  validate: /^\w{3,}/,
  normalize: function (match) {
    match.url = 'https://twitter.com/' + match.url.replace(/^@/, '');
  }
});
```

It could be 
```js
const md = require('markdown-it')({
  html: true,
  linkify: require('linkify-it')()
    .add('@', {
      validate: /^\w{3,}/,
      normalize(match) {
        match.url = 'https://twitter.com/' + match.url.replace(/^@/, '');
      }
    })
    .set('' /* default formatter */, {
      normalize(match) {
        // https://github.com/markdown-it/linkify-it/blob/master/index.js#L614
        if (!match.schema) { match.url = 'https://' + match.url; }

        if (match.schema === 'mailto:' && !/^mailto:/i.test(match.url)) {
          match.url = 'mailto:' + match.url;
        }
      }
    }),
  typographer: true
});
```

if you'd like I can start PR(s) for that
