### ISSUE TITLE
Three hyphens in link breaks link detection

### ISSUE THREAD

**Issue by gregeinfrank** [markdown-it/linkify-it#33]
A link with three consecutive hyphens (`---`) breaks link detection

Example:

http://www.sockwizard.com/counting-sheep---pig-socks.html?utm_source=googlepepla&utm_medium=adwords&id=62181331830&gclid=CISC1NezvswCFYpffgodL9cDrA

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/blob/1.2.1/lib/re.js#L56 not a bug

**Comment by katylava** [comment]
I don't get why you would want this behavior. Is `---` more often used as a long dash than part of a URL?

There is no workaround for this if you want to linkify a URL with three hyphens. However, if recognizing three hyphens as part of the URL was the default behavior, then if you wanted a long dash you could just use spaces around your hyphens, or insert an actual long dash.

**Comment by puzrin** [comment]
@katylava that was done because this linkifier was initially created for `markdown-it` parcer.

Well, since there are no way to properly detect what `---` means in all cases and request is popular, i'll add option and will consider change defaults. See #38

**Comment by puzrin** [comment]
Fixed in 2.0.0
