### ISSUE TITLE
`>` considered as valid symbol instead of punctuation

### ISSUE THREAD

**Issue by puzrin** [markdown-it/linkify-it#4]
```
>example.com
>http://example.com
```

https://github.com/markdown-it/linkify-it/issues/2#issuecomment-76085926

**Comment by MayhemYDG** [comment]
Thanks.

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/commit/b20833215113508e02373fbbfd610c7d49fb10ea

I've added a bit more `symbols` to exclusion for fuzzy links, but not all https://github.com/mathiasbynens/unicode-7.0.0/blob/master/categories/S/regex.js. Don't know if there are any other cases need to be covered.
