### ISSUE TITLE
[ ] is take into account in username which is not defined in https://www.ietf.org/rfc/rfc1738.txt 

### ISSUE THREAD

**Issue by JiechengZhao** [markdown-it/linkify-it#41]
See http://markdown-it.github.io/linkify-it/#t1=%5Bhttps%5D(https%3A%2F%2Fwww.ibm.com)%5Bmailto%5D(mailto%3Asomeone%40ibm.com)%0A%5Bhttps%5D(https%3A%2F%2Fwww.ibm.com%2F)%5Bmailto%5D(mailto%3Asomeone%40ibm.com)
`[https](https://www.ibm.com)[mailto](mailto:someone@ibm.com)`
The result confused us a lot for a while, we finally found out why. 
`www.ibm.com)[mailto](mailto` is regarded as user name and `someone` is the password. `ibm.com` is definitely a valid domain.
However the https://www.ietf.org/rfc/rfc1738.txt doesn't include `[` and `]` as a part of username. 
Seems that this rule is a little too loose 
https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L33

**Comment by puzrin** [comment]
Thanks for report! Published 2.0.1 with fix.

I'd like to clarify - this package does not follow rfc1738 reqs, because it should properly find some human-friendly variations too. But i agree it's a good idea to add more limitations for auth part content. Your example shows problem very well.

**Comment by JiechengZhao** [comment]
Thank you.
