### ISSUE TITLE
Hostnames with hyphens and no TLD are not recognized

### ISSUE THREAD

**Issue by omarestrella** [markdown-it/linkify-it#43]
When you have a hostname that contains no hyphens and no TLD portion (http://localhost), linkify will detect the link and produce the correct anchor tag. When you add a hyphen in the hostname without a TLD (http://local-host), linkify does not recognize it as a link.

Example: http://markdown-it.github.io/linkify-it/#t1=http%3A%2F%2Fhostname%0Ahttp%3A%2F%2Fhost-name%0Ahttp%3A%2F%2Fhost-name.com

**Comment by puzrin** [comment]
Are local hostnames with hyphens valid?

**Comment by omarestrella** [comment]
I am not sure that it matters if it is local or not since hostname can point to a server on the network. All I am going on is the entry from wikipedia:

```
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.
```

I'd understand if you do not want to support this in linkify, but I thought I'd bring it up as an issue in case it was something that was missed.

**Comment by puzrin** [comment]
TLDs and heading parts of domain has different restrictions. That's needed to support "fuzzy" links without protocol.

But general intention is to support links which can really happen in real world and reject artificial things (because euristic can not work well 100% of all possible cases). So, if you really have such links - i'll try to fix. If you have no real link and tried to find something not working - then no fix needed.

**Comment by omarestrella** [comment]
This is something we are seeing in our chat product. People will post link to internal-only servers/machines/devices and they do not get anchored correctly when they contain the hyphen. It just seemed inconsistent to me to support a string like `http://hostname` and not `http://host-name`.

If this is not something you want to add to the core of linkify, is there a hook I can hook into and implement it on my end for our support (through markdown-it)?

**Comment by puzrin** [comment]
Don't worry. I think that will be fixed in nearest week. Your reasons are good enougth.

**Comment by puzrin** [comment]
Fixed by https://github.com/markdown-it/linkify-it/commit/ae3455a6c978a9d34492e42dea857208b9298361
