### ISSUE TITLE
Support for ignoring certain URLs

### ISSUE THREAD

**Issue by Naoto-Ida** [markdown-it/linkify-it#44]
There was a previous discussion on ignoring HTTP with issue #8,
but I was wondering if there is any support for ignoring certain URLs instead of by prefix.
I couldn't find an example of this in the [demo](http://markdown-it.github.io/linkify-it/).

For instance:

[o] https://facebook.com
[x] https://baidu.com

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/blob/master/index.js#L50-L65

Use `.add('http', your_custom_rule)` to override defaults. You can take original code and add your custom conditions.

**Comment by Naoto-Ida** [comment]
Thank you!

**Comment by chmanie** [comment]
Can I disable schemas by just doing

`.add('http', null)` ?

**Comment by puzrin** [comment]
Yes https://github.com/markdown-it/linkify-it#addkey-value
