### ISSUE TITLE
Vertical pipe separators getting included in domain names

### ISSUE THREAD

**Issue by mikelambert** [markdown-it/linkify-it#46]
Some people use a unicode vertical pipe bar as separators.

When it using a traditional ascii vertical pipe, it is *not* included in the URL link:
`sometext|www.dancedeets.com`. (just the www.dancedeets.come becomes a link)

However, when it uses a special unicode vertical pipe (and asian languages/keyboards are more likely to use this character), then linkify-it *does* include it in the URL link:
`sometext｜www.dancedeets.com` (the entire text becomes a link)

I think it's the different-treatment-of-vertical-pipes that bugs me, and what I feel is a bug.

In terms of actual examples of this unicode vertical pipe being used in live text out there (as examples of "de-facto usage of this as a means of humans writing text"), I can point to:
https://www.facebook.com/events/1242414222466166/
https://www.facebook.com/events/228824650884335/
https://www.facebook.com/events/896736620379772/
https://www.facebook.com/events/1012537322116670/
https://www.facebook.com/events/1650303181918755/
https://www.facebook.com/events/1616043775368308/
(and these two do not have public fb events I can point to, so I am pointing to my proxied version of the source text)
http://www.dancedeets.com/events/1056563304381635/2016fun
http://www.dancedeets.com/events/1243934395650908/2016%E6%96%B0%E5%8C%97fun%E8%A1%97%E9%A0%AD%E6%9D%BF%E6%A9%8B%E5%A0%B4%E5%88%9D%E8%B3%BD

**Comment by puzrin** [comment]
Sounds reasonable. I think this can be improved without side effects. Need some clarifications:

1. Could you prepare samples via http://markdown-it.github.io/linkify-it/ ? I could not reproduce correct work with ascii vertical pipe (just copied your texts there).
2. Could you show such patterns at another sites (not facebook)? That's not mandatory condition, but interesting for me.
3. Does this problem happens only with asian pipe before links or with pipe after link too?

**Comment by puzrin** [comment]
And one more question... The most of problems are caused by fact, that link in text can be "incorrect" (not percent-encoded, according to RFC). If anyone needs support only for "correct" links, that can solve a lot of problems (including better asian text recognition). But i have no statistics to decide.

By the way, may be FB linkifier works "better" because of bad support of advanced cases. I'd suggest to post linkifier test cases at facebook to check http://markdown-it.github.io/linkify-it/.

**Comment by mikelambert** [comment]
1) Here's the sample demonstrating the breakage:
http://markdown-it.github.io/linkify-it/#t1=%25%20Regular%20pipes%0A%7Cwww.google.com%2F%0Awww.google.com%2F%7C%0Awww.google.com%2F%7Cwww.google.com%2F%0A%0A%25%20Magic%20pipes%0A%EF%BD%9Cwww.google.com%2F%0Awww.google.com%2F%EF%BD%9C%0Awww.google.com%2F%EF%BD%9Cwww.google.com%2F%0A

(Note that I'm comparing it with the existing pipe, which is considered a "valid" URL path character according to linkify, but not a valid domain character)

2) I'm not taiwanese, and so am not familiar with what taiwanese blogs, sites, etc might demonstrate this character. I run an international site for events, and so I was exposed to these characters (and the taiwanese-authored descriptions) through that. (And because Google told me I had broken links.) If you want, I can point at my site, which proxies the FB event descriptions...but I suspect you're not interested in those links. :)

3) It happens with the unicode pipe after link too. But it happens with the regular pipe after link too. So just matching the regular pipe's behavior, for me, would probably be good enough.

4) Yes, I'm aware that *technically* the standards allow for a variety of unicode characters in domains now, and that it makes the job of domain-name detection very difficult. Especially because unicode-domains are not always encoded (by design! since they look ugly when encoded). But I'm not sure I have any great answers/suggestions here.

For the moment, in my thousands of events (of which only some have URLs), these are the only characters folks were using that generated broken URLs according to Google. So I'm not worried about any more drastic changes/fixes here.

**Comment by puzrin** [comment]
Short summary/memo about possible changes:

1. Full width vertical line `\uFF5C`, can be delimmiter both on start and end of link
   - Need to recheck more delimiter codes from https://github.com/markdown-it/linkify-it/issues/15#issuecomment-105666424.
2. ASCII `|` can be delimiter on start of link (but not on the end, because can exist in query)

**Comment by mikelambert** [comment]
If we're expanding the set of delimiter characters to the chinese ones in https://github.com/markdown-it/linkify-it/issues/15#issuecomment-105666424 

Then in addition to the chinese ones they list `（ ） ， ！ 。 ？ 【 】 ［ ］ 、 《 》 ★`, I would also add the japanese ones `「」『』（）＜＞`. I'm sure there must be a "list of unicode delimiters" somewhere:

[punctuation, open](http://www.fileformat.info/info/unicode/category/Ps/list.htm)
[punctuation, closed](http://www.fileformat.info/info/unicode/category/Pe/list.htm)
[punctuation, open quote](http://www.fileformat.info/info/unicode/category/Pi/list.htm)
[punctuation, close quote](http://www.fileformat.info/info/unicode/category/Pf/list.htm)

I found these from http://www.fileformat.info/info/unicode/category/index.htm

**Comment by puzrin** [comment]
Adding punctuation chars without control can conflict with wikipedia links. Problem is that wiki link can contain almost anything.

**Comment by puzrin** [comment]
I've released version with FF5C char support. Other chars not changed - not enougth info from real world.
