### ISSUE TITLE
Documentation of validator: pos comes after prefix

### ISSUE THREAD

**Issue by edemaine** [markdown-it/linkify-it#47]
I just spent several minutes debugging the use of custom schemas that could have been avoided by better documentation of what a validator function is.  Currently validators are just documented by example.  Specifically, I mistakenly thought that the `pos` argument is where the URL starts, but it's actually the index of just after the prefix.

Similarly, please also document what form a `RegExp` should be.  I was doing `linkify.add('foo', /^foo:[a-z]+/)` but I should have done `linkify.add('foo', /^[a-z]+/)` (for the same reason as above).

**Comment by puzrin** [comment]
Please, do PR with improvements, if you think those are necessary.
