### ISSUE TITLE
Feature request: offer API to automatically add links to a string

### ISSUE THREAD

**Issue by bradvogel** [markdown-it/linkify-it#51]
It look me a while to figure out how to use this library to wrap urls in a string, e.g. `wrapLinks('check out mixmax.com') // returns 'check out <a href="http://mixmax.com">mixmax.com</a>`

Then I found this function from the demo: https://github.com/markdown-it/linkify-it/blob/fb43f47eb0637291aaef3bd162d82efe3f2083d0/support/demo_template/index.js#L22

It'd be nice to have that as a part of the library, for the very common use case of just wrapping urls in anchor tags. The API could be something like:

```
var link = new Linkify({}).linkify('mixmax.com', {
   attributes: {
       target: '_blank'
   }
});
// Returns `<a href="http://mixmax.com" target="_blank">mixmax.com</a>'`
```

**Comment by puzrin** [comment]
I considered such feature on design phase, but decided to not mix pattern search and creating html. For example, you can't just wrap links in any text as you described, but you should escape the rest too. Those demands are very specific to application needs and it's better to keep those separate.

**Comment by bradvogel** [comment]
Would you take a PR to add an example to the readme then?

**Comment by puzrin** [comment]
I'd prefer to keep such task/info separate to keep readme as short as possible. Simple string replacement will be unsafe, and correct manipulation with DOM/AST will not be universal for good example.

May be i don't know some simple solution, but with my current knowledge i can't promiss accepting of such PR.
