### ISSUE TITLE
url with !!! is not detected correctly

### ISSUE THREAD

**Issue by jarindr** [markdown-it/linkify-it#54]
for example

https://google.com/mail/u/0/#label/!!!Today/15c9b8193da01e65

it will return only https://google.com/mail/u/0/#label/ as link

**Comment by puzrin** [comment]
Interesting case. Isn't it too specific? As far as i understand, you can define anything in mailbox label.

**Comment by jarindr** [comment]
@puzrin you are right, but exclamation mark is something we don't actually need to have a pattern to avoid it?

**Comment by puzrin** [comment]
`Go to http://this.link!!!` - !!! should be excluded

**Comment by puzrin** [comment]
There are condition for `!` https://github.com/markdown-it/linkify-it/blob/2.0.3/lib/re.js#L71 (and tests), but those do not cover your case.

**Comment by puzrin** [comment]
Sorry, reverted fix due collision. See commited sample.
