### ISSUE TITLE
URL not detected correctly

### ISSUE THREAD

**Issue by cesarfd** [markdown-it/linkify-it#60]
It is an unusually long url: https://runkit.com/embed/msue73ku8uor

There's a part in the url, `hYnNlZw.._Jcrrel`. It seems the parser stops considering anything pass the `..` string.

**Comment by puzrin** [comment]
This package is for human-readable texts, not for any possible autogenerated URLs. I would not change mainstream rules, but you can fix those in your own fork, all regexps are commented.

**Comment by cesarfd** [comment]
Anyway, it seems that the problem is not the `..` but the `.._`. That's what somehow breaks the parsing. Any idea what should I modify to make it work?

Is it in `re.src_path`?

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it/blob/cbc0833d3355dc04122c7a666122a61e58392555/lib/re.js#L59

**Comment by cesarfd** [comment]
Thank you! 

It worked just by changing it to `\\.{2,3}[a-zA-Z0-9%_/]|` ¡. I guess you prefer to keep it your way, right?

**Comment by cesarfd** [comment]
Solved https://github.com/markdown-it/linkify-it/pull/81
