### ISSUE TITLE
Linking fails for links with three dots in the url

### ISSUE THREAD

**Issue by maynardewm** [markdown-it/linkify-it#66]
https://www.google.com/search?source=hp&ei=y0QtW7yUGpiq0PEPv5qv8Ag&q=best+sci+fi+books&oq=best+sci&gs_l=psy-ab.3.1.0j0i20i264k1j0j0i131k1j0l6.2035.4079.0.5985.9.8.0.0.0.0.132.797.5j3.8.0....0...1c.1.64.psy-ab..1.8.797.0..35i39k1j0i67k1.0.iug3EHWIyxc

Linkify fails to wrap the a tag around the entire link at the point of the first three dots in a row. Or in this case, 4 dots.

**Comment by ex3ndr** [comment]
Any workarounds?
