### ISSUE TITLE
URL with more than one exclamation mark breaks

### ISSUE THREAD

**Issue by realies** [markdown-it/linkify-it#69]
As the title states, URL detection stops at the first instance of more than one exclamation mark.

**Comment by christer88** [comment]
**Example:**
https://img.alicdn.com/imgextra/i4/128600268/TB2iGrkacwb61Bjy0FfXXXvlpXa_!!128600268.jpg

**Comment by astorije** [comment]
Maybe related to #63?

**Comment by puzrin** [comment]
Dupe of #54
