### ISSUE TITLE
Better email re?

### ISSUE THREAD

**Issue by puzrin** [markdown-it/linkify-it#7]
https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L59

Current email nick regex is very primitive. It it ok or something better needed?

__upd: please, post the real examples, that's the most valuable info__

**Comment by Kagami** [comment]
I think no. It's *VERY* hard to validate email per RFC (especially if you don't want to go crazy [like this](http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html)):
http://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/

**Comment by Kagami** [comment]
[This article](http://davidcel.is/blog/2012/09/06/stop-validating-email-addresses-with-regex/) even recommends just `/@/` and I can't disagree with its thesises.

**Comment by puzrin** [comment]
I'd like to get the real (not artificial) examples of wrong results. That will be the best info to make decisions.

**Comment by Kagami** [comment]
"Real" is subjective. It can work in some cases and won't work in others. That's what RFCs are for.
Though, this is just my two cents.

**Comment by puzrin** [comment]
All this package logic is subjective. Only real examples are useful. Updated first post info.

**Comment by puzrin** [comment]
Closing. Nobody cares :)
