### ISSUE TITLE
Match link prefix without a whitespace in front?

### ISSUE THREAD

**Issue by b1acKr0se** [markdown-it/linkify-it#70]
First of all, thank you for this awesome library. I'm using it in combination with https://github.com/obipawan/react-native-hyperlink .

I'm having an use case which involves linkify hashtags inside a string. The setup is done by using the `add` method:
```
this.linkifyIt.add('#', {
        validate: function (text, pos, self) {
        //doing the validation
     })
```
Now it works well if there is a space in front of the hashtag, like `This is a #hashtag`.
But in the case there is none, like `hashtag#hashtag`, the validation function is not even called.
Also I need it with special case like this `####hashtag1####hashtag2` to result in `#hashtag1` and `#hashtag2` being detected, but I have no luck.

What should I do for these cases?  Thank you for taking your time to read through this :D

**Comment by b1acKr0se** [comment]
@puzrin That's unfortunate, guess I'll have to find another way. Thanks for your response 😄

**Comment by Liqiankun** [comment]
@b1acKr0se Did you solve this issue?
