### ISSUE TITLE
Disable URI encoding

### ISSUE THREAD

**Issue by christianbundy** [markdown-it/linkify-it#71]
I have a weird use-case where we link to `/%abc` and do *not* have URI-encoding. Here's what `match` looks like after normalization:

```js
{
  schema: '%',
  index: 0,
  lastIndex: 52,
  raw: '%f89BLtbzADRFO5FaC4ktwzyI0FjCTjKtnzJBzKW5rio=.sha256',
  text: '%f89BLtb',
  url: '%f89BLtbzADRFO5FaC4ktwzyI0FjCTjKtnzJBzKW5rio=.sha256'
}
```

Unfortunately `text` is being mangled and `%f8` is being URI-decoded, whereas I'd like that to be a string literal. If we replace the `%` with `%25` then the `url` becomes mangled, and the `%` is being URI-encoded as `%25` as well. Is there a way to disable the codec behavior?

---

To be clear, this is being rendered as:

```html
<a href="%f89BLtbzADRFO5FaC4ktwzyI0FjCTjKtnzJBzKW5rio=.sha256">�9BLtb</a>
```

When we fix the `text` property it seems to be affecting the `url` property, because then it comes out as:

```html
<a href="%25f89BLtbzADRFO5FaC4ktwzyI0FjCTjKtnzJBzKW5rio=.sha256">%f89BLtb</a>
```

The desired behavior is:

```html
<a href="%f89BLtbzADRFO5FaC4ktwzyI0FjCTjKtnzJBzKW5rio=.sha256">%f89BLtb</a>
```

Our code is:

```js
['@', '%', '&'].forEach(sigil => {
    md.linkify.add(sigil, {
      validate: function (text, pos, self) {
        var tail = text.slice(pos)

        if (!self.re.sigil) {
          self.re.sigil = new RegExp(
            '^([a-zA-Z0-9+/=]{44}.[a-z0-9]+)'
          )
        }
        if (self.re.sigil.test(tail)) {
          return tail.match(self.re.sigil)[0].length
        }
        return 0
      },
      normalize: function (match) {
        // shorten the link to 7 characters plus the sigil
        match.text = match.text.slice(0, 8)
        // linkify is percent-decoding, so we percent-encode the percent symbol
        match.text = match.text.replace(/^%/, '%25')
        match.url = config.toUrl(match.raw)
        console.log(match)
      }
    })
  })
```

**Comment by puzrin** [comment]
I'd suggest to inspect sources, because there are many possibilities for modifications. The most simple is to override default method

https://github.com/markdown-it/linkify-it/blob/cbc0833d3355dc04122c7a666122a61e58392555/index.js#L610-L625

**Comment by christianbundy** [comment]
@puzrin Sorry, maybe I didn't edit quickly enough -- I'm using the `normalize` method, but it seems like there's some interplay between `match.text` and `match.url` where modifying the text mangles the URL. I'd like to be able to set `match.text = '%25'` and have that produce `<a>%25</a>` rather than `<a>%</a>`.

**Comment by puzrin** [comment]
If you think there is some interplay, you could provide a minimal possible executable code sample, as proof of reproducible problem.

This package just search text bounds and add some meta, any post-processing magic is out of scope.

**Comment by christianbundy** [comment]
Thanks, I think this was just happening in `link_open` in markdown-it -- I'll post-process after that step is done, thanks a lot!
