### ISSUE TITLE
Is it possible to match add a rule definition based on suffix?

### ISSUE THREAD

**Issue by Aerlinger** [markdown-it/linkify-it#76]
Is it possible to add a schema rule based on the suffix of a word? For example, I'm looking to transform a username string of the form `username@` to a url (e.g. something http://github.com/username).

It looks like the [`.add` function](http://markdown-it.github.io/linkify-it/doc/#LinkifyIt.prototype.add) matches a rule based on the prefix of a word only, so wasn't sure if this is possible.

**Comment by puzrin** [comment]
No, there are some limitations, because all this should work "fast".
