### ISSUE TITLE
Disable default schemas

### ISSUE THREAD

**Issue by Kagami** [markdown-it/linkify-it#8]
Hi. Great library!

Is it possible to disable default schemas without hacking the `__schema__` property or providing some dummy matcher? For example I may want to disable `ftp:` schema. It would be great to have the ability to spawn `LinkifyIt` like this:

```js
LinkifyIt({http: true, https: true});  // only default http and https rules
LinkifyIt(false);  // disable all schemas
```

Thanks.

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkify-it#addschema-definition

`.add('ftp:', null)`

**Comment by Kagami** [comment]
Thanks, but what about disabling all default schemas?

**Comment by vyp** [comment]
@Kagami a loop? (if I understand correctly?)

**Comment by Kagami** [comment]
@vyp Loop over that? If I hardcoded current default schemas, it's possible there would be new in the future. Or I just can loop throught internal `__schemas__` property but I meant some official API.

**Comment by puzrin** [comment]
If you need new functionality - provide examples, why it will be useful for all. I can't imagine how full reset can be used.

**Comment by vyp** [comment]
@Kagami you're correct. I don't think there is an api for this right now.

@puzrin I think kagami wants to ensure that *only* http(s) links are linkified, ignoring everything else.

**Comment by Kagami** [comment]
>I think kagami wants to ensure that only http(s) links are linkified, ignoring all other schemas.

Yea, sorry if it was unclear. I want to have some whitelisted protocols and make sure new versions of linkify-it won't automatically add new default schemas.

**Comment by puzrin** [comment]
You can be sure, that default list will not be extended. I think that will not happen even after major version bump.

**Comment by Kagami** [comment]
Ok, thanks!
