### ISSUE TITLE
URL italicized

### ISSUE THREAD

**Issue by fabiospampinato** [markdown-it/linkify-it#80]
A portion of the following URL get italicized ([demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22http%3A%2F%2Fexample.com%2F_foo_%2Fbar%2Fbaz%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)):

```
http://example.com/_foo_/bar/baz
```

**Comment by puzrin** [comment]
That's a known issue, discussed many times in markdown tracker, not planned for fix. Not a bug of this package.
