### ISSUE TITLE
Fully qualified domains are not fully parsed

### ISSUE THREAD

**Issue by xPaw** [markdown-it/linkify-it#83]
Example: https://markdown-it.github.io/linkify-it/#t1=http%3A%2F%2Fjdebp.info.%2FFGA%2Fweb-fully-qualified-domain-name.html%0Ahttp%3A%2F%2Fjdebp.info.%0Ahttp%3A%2F%2Fjdebp.info.%2F

Github handles it:
http://jdebp.info./FGA/web-fully-qualified-domain-name.html
http://jdebp.info./
http://jdebp.info. (no dot in url on github)
http://jdebp.info.#test

Unsure if it's an easy fix without breaking anything else.

**Comment by puzrin** [comment]
- `http://jdebp.info.` - this case can not be resolved without false positives.
- `http://jdebp.info./FGA/web-fully-qualified-domain-name.html` - this can be fixed.

So, prior to do anything, we need to answer question:

- Are such examples for real world? Do we really need to fix that?
- Will partial fix help?

**Comment by xPaw** [comment]
> http://jdebp.info. - this case can not be resolved without false positives.

I agree, and I wouldn't touch it (github doesn't either).

I would be fine with supporting dots when there's a path (so realistically look for `./`?)

The link I provided would be one such real world example :)

**Comment by puzrin** [comment]
> The link I provided would be one such real world example :)

I would disagree. The link you provided mean this is "technically possible". I think, i could invent many special cases, when linkifier fails. But technically possible != really used.

Could you explain, where (why?) people use such links as "normal case" without intent to break something?

**Comment by puzrin** [comment]
Closing as timed out (no feedback). But can be reopened anytime if actual & required. Feel free to add your comments.
