### ISSUE TITLE
Linkify wraps images in []() making them unusable

### ISSUE THREAD

**Issue by AggressivelyMeows** [markdown-it/linkify-it#85]
When using Linkify, it wraps images in []() which makes them invalid.

In the demo, this is clearly shown by doing `![](https://cdn.ceru.tech/sponsus/1729788214794915840/1745970052907274240.png)`. The image tag is linkify'ed which makes it invalid and render as `<img src="[image_url](image_url)"/>`

![](https://i.imgur.com/M0FHVAS.png)

**Comment by puzrin** [comment]
That's not a bug. It searches url-like ranges and it's only your responsibility how to use those. Linkifier works with plain text and does not know enything about more high-level formatting.
