### ISSUE TITLE
Doesn't seem to support domain-specific rules

### ISSUE THREAD

**Issue by Friction-less-development** [markdown-it/linkify-it#89]
As far as I can tell it seems that this library doesn't allow you to add transformation rules for specific domains.

For example if you wanted to transform all youtube links to embedded videos. Or twitter links to embedded components.

Any thoughts, should I try my hand at it?

**Comment by puzrin** [comment]
This is out of this package scope.

See https://github.com/nodeca/embedza or similar things.
