### ISSUE TITLE
Linkify breaks a link when it contains a sequence of dots

### ISSUE THREAD

**Issue by Leonya** [markdown-it/linkify-it#9]
```
http://www.hostname.com/123.123
``` 

is linkified correctly, 

```
http://www.hostname.com/123..123
```

is not - the part after the first "." is not included in the href or link text.

**Comment by puzrin** [comment]
IMHO in case of 2,3 and more dots user can really wish to have link + dots + text. If you know additional condition how to avoid false positives in all languages - let me know.

Full logic for path is here https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L36-L55

**Comment by puzrin** [comment]
Do you have examples of live sites, having multiple dots in links? That should help to collect statictics.

**Comment by Leonya** [comment]
I don't know, I think a link should be a link until a space or another invalid character is encountered – with very few exceptions, such as a link in round/square brackets or quotation marks.

**Comment by Leonya** [comment]
Of course I have. It's used on this very website. For example, https://github.com/codemirror/CodeMirror/compare/mobile...master

I need it for https://www.jetbrains.com/upsource/ for the same purpose.

**Comment by puzrin** [comment]
Ok. All github links with commit ranges. Thanks for good example.
