### ISSUE TITLE
Inconsistent link recognition when wrapped within html element

### ISSUE THREAD

**Issue by benkeen** [markdown-it/linkify-it#90]
Great library. However, I ran into a small issue & I don't think it's a configuration problem on my end. 

When running linkify on each of these two lines, it's able to find the link in the first one but not the second. I haven't disabled the fuzzy option. 

```html
<div>http://google.com</div>
<div>google.com</div>
```

Removing the wrapper `<div>` elements makes the script find the links on both lines.

**Comment by puzrin** [comment]
This linkifier is not magical thing to understand any possible input format. It search links in human-readable texts only. If you use html - you shold parse it and apply linkifier to  every text component.

**Comment by benkeen** [comment]
Thanks for the response. :)
