### ISSUE TITLE
url with !! is not detected correctly

### ISSUE THREAD

**Issue by iEricKoh** [markdown-it/linkify-it#92]
url:
> https://www.baopals.com/search/imgextra%2Fi1%2F113230311%2FO1CN015pfw7P1EATmYFN0ro_!!113230311%26%2346%3Bjpg

only this part was parsed into a link:
> https://www.baopals.com/search/imgextra%2Fi1%2F113230311%2FO1CN015pfw7P1EATmYFN0ro_

**Comment by puzrin** [comment]
https://markdown-it.github.io/linkify-it/#t1=https%3A%2F%2Fgoogle.com%2Fmail%2Fu%2F0%2F%23label%2F!!!Today%2F15c9b8193da01e65%0A%0Ahttps%3A%2F%2Fwww.baopals.com%2Fsearch%2Fimgextra%2Fi1%2F113230311%2FO1CN015pfw7P1EATmYFN0ro_!!113230311%26%2346%3Bjpg

Can not reproduce (and appropriate test exists, #54)
