### ISSUE TITLE
URLs with period and parantheses stop before closing parentheses

### ISSUE THREAD

**Issue by JeremyMahieu** [markdown-it/linkify-it#94]
Links such as

- `https://foo.com/bar.(par)` result in `https://foo.com/bar.(par`
- `https://foo.com/bar.(par).asdf` result in `https://foo.com/bar.(par`

For example real world links can be file shares that replace spaces in filenames with periods. (note: I have no affiliation with the link or the content, just found on google when searching for "Index of"

- `http://index-of.es/Android/Professional.Android.2.Application.Development.(Wrox,.2010,.0470565527).pdf`

**Comment by nmilev-scribe** [comment]
Having the same issue.
How to reproduce:
paste the url below into the lounge demo:
```
https://mixpanel.com/project/2224040/view/2771788/app/insights#report/28200585/kp-is/~(columnWidths~(bar~())~description~'~displayOptions~(chartType~'line~plotStyle~'standard~analysis~'linear~value~'absolute)~sorting~(bar~(sortBy~'column~colSortAttrs~(~(sortBy~'value~sortOrder~'desc)))~line~(sortBy~'value~sortOrder~'desc~valueField~'averageValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'averageValue)))~table~(sortBy~'column~colSortAttrs~(~(sortBy~'label~sortOrder~'asc)))~insights-metric~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'totalValue)))~pie~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'totalValue))))~timeComparison~null~querySamplingEnabled~false~dashboard~(id~2868932~title~'NTRS*20*281000*29~creator_name~'Caila*20MacDonald~can_update_basic~true~can_share~true~allow_staff_override~false~is_superadmin~false)~title~'KPIs~sections~(show~(~(datase
```

**Comment by rlidwka** [comment]
Fixed examples like `foo.(bar)`, `foo;[bar]` and similar (with punctuation followed by some sort of parenthesis).

For deeply nested parens we don't have a solution, see https://github.com/markdown-it/linkify-it/issues/23

**Comment by nmilev-scribe** [comment]
@rlidwka Which version contains this fix?
