### ISSUE TITLE
Links with slashes capturing trailing semicolons

### ISSUE THREAD

**Issue by georgediaz88** [markdown-it/linkify-it#98]
Hi,

Using the [demo site](http://markdown-it.github.io/linkify-it/), I noticed links with slashes capturing trailing semicolons. This works well for trailing periods but not for trailing semicolons as I expected. Here are some examples:

1. Trailing period after slash. Works as expected:

```
www.google.com/.

=> www.google.com/
```

2.  Trailing semicolon, no slash. Works as expected:

```
www.google.com;

=> www.google.com
```

3. Trailing period after slash. Works as expected:

```
www.google.com/.

=> www.google.com/
```

4. Semicolon after slash. Doesn't work as expected:

```
www.google.com/;

=> www.google.com/;

(I would've expected it to capture like `www.google.com/`)
```

Is the last example above by design? There are some academic disciplines that separate a list of urls with semicolons. So, that's the behavior we're trying to match with this plugin.

Your help would be greatly appreciated.

Thanks!
George

**Comment by puzrin** [comment]
> Is the last example above by design? There are some academic disciplines that separate a list of urls with semicolons. So, that's the behavior we're trying to match with this plugin.

Euristic algorythms can not guarantee right result for 100%.

`;` is valid char for URL. I see 2 alternatives:

- You can patch regexp-s in your clone as you need, with some risk to break other cases
- Try to provide formal description how to decide when `;` should not be part of url, without side-effects.

**Comment by georgediaz88** [comment]
Hi @puzrin,

Thanks for your quick response.

Regarding:

> Try to provide formal description how to decide when ; should not be part of url, without side-effects.

The way it could work would be just like you noted, exactly:  "PS. At first glance, "; can not be part of link, if followed with space" - may work." 

Here are some real world examples:

*See* Nathan Bomey & Marco della Cava, *Sexual Harassment Went Unchecked for Decades as Payouts Silenced Accusers*, USA Today (Dec. 1, 2017), https://www.usatoday.com/story/money/business/2017/12/01/sexual-harassment-went-unchecked-decades-payouts-silenced-accusers/881070001/; Lyn Yonack, *Sexual Assault Is About Power: How #MeToo Campaign Is Restoring Power to Victims*, Psychol. Today (Nov. 14, 2017), https://www.psychologytoday.com/us/blog/psychoanalysis-unplugged/201711/sexual-assault-is-about-power.

*See* Carl Hulse, *Political Polarization Takes Hold of the Supreme Court*, N.Y. Times (July 5, 2018), https://www.nytimes.com/2018/07/05/us/politics/political-polarization-supreme-court.html; Kevin Schaul & Kevin Uhrmacher, *Analysis:* *How Trump Is Shifting the Most Important Courts in the Country*, Wash. Post (Sept. 4, 2018),

The role that *per curiam* decisions do and should play, particularly when the Court does not speak with a unified voice, is quite interesting and a topic for further exploration. *See* https://www.theatlantic.com/ideas/archive/2018/06/the-court-slices-a-narrow-ruling-out-of-masterpiece-cakeshop/561986/; Ira P. Robbins, *Hiding Behind the Cloak of Invisibility: The Supreme Court and Per Curiam Opinions*, 86

 *See* David Orr, *Poets, Academia: A Couplet in Conflict*, N.Y. Times (May 30, 2009), https://www.nytimes.com/2009/05/31/weekinreview/31orr.html; Steven L. Winter, *Death Is the Mother of Metaphor*, 105 Harv. L. Rev. 745, 749--50 (1992) (describing poet Wallace Stevens's relationship to the study of law and legal language).

You'll also see Github excludes the trailing semicolon from these links as expected. 

Currently, our users end up correcting links like these in our markdown by setting a markdown link with everything in the link excluding the trailing semicolon. Of course, it would be best if this library handled this scenario to solve that pain point.

Let me know what you think.

Thanks!
George

**Comment by puzrin** [comment]
Try v3.0.3

**Comment by georgediaz88** [comment]
@puzrin, whoa this is awesome!! 🎉 

IT WORKS!

I appreciate you quickly adding this for me / my team. Thank you!
